DETAIL: FALSE
IMPLEMENT: tensorflow
HW: 28
CIN: 64
SHAPE_1D: 428
COUT: 128
KERNEL_SIZE: 3
PADDING: 'same'
STRIDES: 1
POOL_STRIDES: 2
EMP_ALPHA: 0.5
BASIC_TESTCASES:
  - add_add
  - add_avgpool
  - add_concat
  - add_conv
  - add_convtrans
  - add_dwconv
  - add_fc
  - add_relu
  - add_reshape
  - avgpool_add
  - avgpool_avgpool
  - avgpool_concat
  - avgpool_conv
  - avgpool_convtrans
  - avgpool_dwconv
  - avgpool_relu
  - avgpool_reshape
  - bn_relu
  - concat_add
  - concat_avgpool
  - concat_concat
  - concat_conv
  - concat_convtrans
  - concat_dwconv
  - concat_fc
  - concat_relu
  - concat_reshape
  - conv_add
  - conv_avgpool
  - conv_bn
  - conv_concat
  - conv_conv
  - conv_convtrans
  - conv_dwconv
  - conv_hswish
  - conv_relu
  - conv_reshape
  - conv_se
  - convtrans_add
  - convtrans_avgpool
  - convtrans_concat
  - convtrans_conv
  - convtrans_convtrans
  - convtrans_dwconv
  - convtrans_relu
  - convtrans_reshape
  - dwconv_add
  - dwconv_avgpool
  - dwconv_bn
  - dwconv_concat
  - dwconv_conv
  - dwconv_convtrans
  - dwconv_dwconv
  - dwconv_relu
  - dwconv_reshape
  - fc_add
  - fc_concat
  - fc_fc
  - fc_relu
  - fc_reshape
  - relu_add
  - relu_avgpool
  - relu_concat
  - relu_conv
  - relu_convtrans
  - relu_dwconv
  - relu_fc
  - relu_relu
  - relu_reshape
  - reshape_add
  - reshape_avgpool
  - reshape_concat
  - reshape_conv
  - reshape_convtrans
  - reshape_dwconv
  - reshape_fc
  - reshape_relu
  - reshape_reshape
  - se_relu
OTHER_TESTCASES:
  - MON
LAYERS_1D:
  - fc